env:
  browser: true
  es2021: true
extends:
  - airbnb
  - plugin:react/recommended
  - plugin:react/jsx-runtime
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
  react/jsx-uses-react: off  # plugin:react/jsx-runtime wont work in vscode
  react/react-in-jsx-scope: off  # plugin:react/jsx-runtime wont work in vscode
  react/jsx-props-no-spreading: off  # Spreading is useful
  jsx-a11y/label-has-associated-control: off  # Turned off due to modern label syntax wont work in vscode
  arrow-parens:
    - error
    - 
      as-needed
  max-len:
    - warn
    -
      code: 120
      ignoreComments: true
      ignoreTrailingComments: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
settings: 
  import/resolver:
    node:
      moduleDirectory:
        - src
        - node_modules
