services:
  backend-dev:
    image: backend-dev
    build:
      context: backend/
      target: debug
    command:
      - "sh"
      - "-c"
      - |
        alembic upgrade head \
        && python ./src/db/init_db.py \
        && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 \
        -m uvicorn src.main:app --reload --host 0.0.0.0
    ports:
      - 5678:5678
      - 8000:8000
    volumes:
      - ./backend/src/:/app/src/
      - ./backend/alembic/:/app/alembic/
    env_file:
      - .env
    depends_on:
      - postgres-dev

  # frontend-dev:
  #   image: frontend
  #   build:
  #     context: frontend/
  #     target: debug
  #   volumes:
  #     - ./frontend/src/:/app/src/
  #   env_file:
  #     - .env
  #   ports:
  #     - 3000:3000
  #     - 9229:9229
  #   command: yarn start --inspect=0.0.0.0:9229
