services:
  backend:
    build: backend
    command: ["sh", "-c", "alembic upgrade head && pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --reload --host 0.0.0.0 --app-dir src"]
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: 'postgresql+asyncpg://postgres:TODO_CHANGE_ME@postgres:5432/postgres'
    depends_on:
      - postgres
